config:
  path: ~/.config/kms/config.yaml

database:
  path: ~/.local/share/kms/{}.db

keyfile:
  path: ~/.local/share/kms/{}.key
  content: |
    <?xml version="1.0" encoding="UTF-8"?>
    <KeyFile>
    <Meta><Version>1.00</Version></Meta>
    <Key><Data>{}</Data></Key>
    </KeyFile>

encryption:
  path: ~/.local/.snc/.{}

rules:
  password:
    min_length: 64
    characters:
      - "A-Z"
      - "a-z"
      - "0-9"
      - "#$%&@^`~"
      - '.,:;'
      - "\"'"
      - "\/|_-"
      - "<>*+!?="
      - "{[()]}"


